plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.hilt) apply false
}

subprojects {
    configurations.configureEach {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.jetbrains.kotlin" &&
                requested.name == "kotlin-metadata-jvm"
            ) {
                // Hilt ships an older metadata reader; GeckoView/Kotlin 2.3 need a newer one.
                useVersion("2.3.10")
                because("Read Kotlin 2.3 metadata generated by current toolchain")
            }
        }
    }
}
